fix(onedrive): check response content type before trying to parse JSON
adobe/helix-onedrive-support pull request #152
Opened 2021-04-07 08:34 UTC by dominique-pfister

fix #151

2021-04-07 08:39 UTC, tripodsan commented on src/OneDrive.js
> +      return await (rawResponseBody || !json ? resp.buffer() : resp.json());
in this case, the caller always needs to check if the response is a buffer or a (json) object.

2021-04-07 08:41 UTC, tripodsan requested changes
not sure about the new version. in any case, also adjust the documentation

2021-04-07 08:46 UTC, stefan-guggisberg approved these changes

2021-04-07 09:15 UTC, dominique-pfister commented
> not sure about the new version. in any case, also adjust the documentation

I can also change the `Table.delete` to pass **true** for the `rawResponseBody` parameter, which would fix the issue as well.

2021-04-07 09:17 UTC, dominique-pfister commented
> ... also adjust the documentation

OneDrive.doFetch is currently undocumented...

2021-04-07 09:35 UTC, dominique-pfister commented
Changed code on the "client" side: identified all APIs that return an empty response, and therefore need no JSON parsing.

2021-04-07 10:25 UTC, tripodsan commented
> > ... also adjust the documentation
> 
> `OneDrive.doFetch` is currently undocumented...

well then!

2021-04-07 10:28 UTC, tripodsan requested changes
well, I think throwing an error if the response is not a json is wrong.
then rather having the `buffer|object` ambiguety.

2021-04-07 11:48 UTC, stefan-guggisberg approved these changes

2021-04-07 12:02 UTC, stefan-guggisberg commented
> > > ... also adjust the documentation
> > 
> > 
> > `OneDrive.doFetch` is currently undocumented...
> 
> well then!

@tripodsan The exposed `OneDrive` API always was and still is largely undocumented, see [here](https://github.com/adobe/helix-onedrive-support/blob/main/docs/API.md#OneDrive). This PR addresses a specific issue (#151). Lack of documentation should IMO be addressed in a separate issue/PR.

2021-04-07 12:33 UTC, dominique-pfister commented
> well, I think throwing an error if the response is not a json is wrong.
> then rather having the `buffer|object` ambiguety.

fair enough, so I added that check back

2021-04-08 00:18 UTC, tripodsan commented
> @tripodsan The exposed `OneDrive` API always was and still is largely undocumented, see [here](https://github.com/adobe/helix-onedrive-support/blob/main/docs/API.md#OneDrive). This PR addresses a specific issue (#151). Lack of documentation should IMO be addressed in a separate issue/PR.

I know... but when changing the behaviour of the api, we could gradually add more documentation.... at least adjust the signature in the types.

2021-04-08 00:20 UTC, tripodsan approved these changes

2021-04-08 06:23 UTC, merged

2021-04-08 08:29 UTC, stefan-guggisberg commented
> at least adjust the signature in the types.

I agree, and that's what I did :-) 

https://github.com/adobe/helix-onedrive-support/commit/2c400724bd5e65a8953c0258d4f676e6b566d145#diff-e8aa1fc0f32bbe7c1f688d6f8259634a0fc7b046ec10b6ab66102847d51b632fR123-R125