feat: add rate limit in log and StatusCodeError
adobe/helix-onedrive-support pull request #394
Opened 2023-06-04 09:45 UTC by dominique-pfister

2023-06-04 09:46 UTC, dominique-pfister commented on src/RateLimit.js
> +  }
conventient, still not sure whether to include LFs in the string representation

2023-06-04 09:46 UTC, dominique-pfister commented on src/excel/NamedItemContainer.js
> +        throw new StatusCodeError(e.message, 409);
this was actually badly constructed (there was never a 4th arg to the `StatusCodeError` constructor), but still the test succeeded

2023-06-04 16:47 UTC, tripodsan approved these changes

2023-06-04 16:48 UTC, tripodsan commented on src/RateLimit.js
> +    let s = `\n  limit: ${this.limit}\n  remaining: ${this.remaining}\n  reset: ${this.reset} seconds`;
wouldn't this better be a json like string?

2023-06-04 16:49 UTC, tripodsan requested changes
we should also return the 429 and the `retry-after` from the admin response

2023-06-05 08:09 UTC, tripodsan commented
> we should also return the 429 and the `retry-after` with the admin response

never mind... I was confused :-)

2023-06-05 08:24 UTC, tripodsan commented on src/RateLimit.js
> +  }
```suggestion
  toJSON() {
    const o = {
      limit: this.limit,
      remaining: this.remaining,
      reset: this.reset,
    };
    if (this.retryAfter) {
      o.retryAfter = this.retryAfter;
    }
    return o;
  }
  
  toString() {
      return JSON.stringify(this);
  }
```

2023-06-05 08:25 UTC, tripodsan commented on src/OneDrive.js
> +        this.log.warn(`Rate limit reported: ${rateLimit.toString()} for tenant: ${this.auth.tenant}`);
```suggestion
        this.log.warn({ sharepointRateLimit: { tenant: this.auth.tenant, ...rateLimit.toJSON() }});
```

2023-06-05 08:26 UTC, tripodsan commented on src/RateLimit.js
> +  }
the `toString()` is probably not needed anymore

2023-06-05 08:36 UTC, merged