fix: store session in workbook
adobe/helix-onedrive-support pull request #450
Opened 2023-10-13 16:11 UTC by dominique-pfister

2023-10-13 16:12 UTC, dominique-pfister commented on src/OneDrive.js
> -
get rid of global session id

2023-10-13 16:12 UTC, dominique-pfister commented on src/excel/Workbook.js
> +    }
pass session-id if available

2023-10-13 16:13 UTC, dominique-pfister commented on src/excel/Workbook.js
> +    const result = await this.doFetch(`${this._uri}/worksheets`);
call our own implementation that will add the session id

2023-10-13 16:13 UTC, dominique-pfister commented on src/excel/Workbook.js
> +    return new Table(this, `${this._uri}/tables`, name, this._log);
pass `us` as doFetch implementor

2023-10-13 20:16 UTC, tripodsan requested changes
- ensure the commit will be breaking
- adjust types

2023-10-14 06:23 UTC, dominique-pfister commented
> * ensure the commit will be breaking

why is it breaking? the API did not change

> * adjust types

what types?

2023-10-14 06:37 UTC, tripodsan commented
> > * ensure the commit will be breaking
> 
> why is it breaking? the API did not change

<img width="524" alt="image" src="https://github.com/adobe/helix-onedrive-support/assets/917628/529aa02f-056e-4e04-8fe3-b8f40c998c9f">

> 
> > * adjust types
> 
> what types?

https://github.com/adobe/helix-onedrive-support/blob/main/src/excel/Workbook.d.ts

but I see that the `OneDrive.getWorkbookSessionId` was never documented.

2023-10-14 06:38 UTC, tripodsan commented on src/excel/Workbook.js
>    async createSession() {
this is a bit ugly... I would throw an exception if a session id already exists and add a `getSessionId()`

2023-10-14 06:47 UTC, dominique-pfister commented on src/excel/Workbook.js
> +    this._sessionId = sessionId;
reject setting session

2023-10-14 06:48 UTC, dominique-pfister commented on src/excel/Workbook.js
> +      throw new StatusCodeError('This workbook is already associated with a session', 400);
reject overwriting session

2023-10-14 07:00 UTC, dominique-pfister commented on src/excel/Workbook.js
>    }
allow to get session id

2023-10-14 07:03 UTC, tripodsan approved these changes

2023-10-14 07:04 UTC, merged